#!/usr/bin/env bash
set -euo pipefail

# Assembles the standalone `swift-lodedb` SwiftPM package into <staging_dir>: the Swift
# sources from this repo plus a root Package.swift whose binaryTarget points at the
# released LodeDBCoreFFI.xcframework. The release workflow then commits, tags, and
# pushes <staging_dir> to the package repo. Kept separate from the git push so the
# assembly is runnable/inspectable locally.
#
# Usage:
#   publish_swift_package.sh <staging_dir> <version> <xcframework_zip_url> <checksum>
#
# - <version> is the numeric version (e.g. 1.1.0), used for the README and (by the
#   caller) the package-repo tag `v<version>`.

staging="${1:?usage: publish_swift_package.sh <staging_dir> <version> <xcframework_zip_url> <checksum>}"
version="${2:?missing version}"
url="${3:?missing xcframework zip url}"
checksum="${4:?missing checksum}"

repo_root="$(cd "$(dirname "$0")/../../.." && pwd)"
package_dir="${repo_root}/swift/LodeDBCore"

mkdir -p "${staging}"
rm -rf "${staging}/Sources"
cp -R "${package_dir}/Sources" "${staging}/Sources"
cp "${repo_root}/LICENSE" "${staging}/LICENSE"
[ -f "${repo_root}/NOTICE" ] && cp "${repo_root}/NOTICE" "${staging}/NOTICE"

cat > "${staging}/Package.swift" <<EOF
// swift-tools-version: 5.9
//
// Standalone LodeDBCore Swift package, version ${version}.
// Generated by the LodeDB release workflow (swift/LodeDBCore/scripts/publish_swift_package.sh);
// do not edit by hand. Sources and issues live in https://github.com/Egoist-Machines/LodeDB.

import PackageDescription

let package = Package(
    name: "LodeDBCore",
    platforms: [
        .macOS(.v13),
        .iOS(.v16)
    ],
    products: [
        .library(name: "LodeDBCore", targets: ["LodeDBCore"])
    ],
    targets: [
        .binaryTarget(
            name: "LodeDBCoreFFI",
            url: "${url}",
            checksum: "${checksum}"
        ),
        .target(
            name: "LodeDBCore",
            dependencies: ["LodeDBCoreFFI"],
            linkerSettings: [
                .linkedFramework("Accelerate")
            ]
        )
    ]
)
EOF

cat > "${staging}/README.md" <<EOF
# LodeDBCore (Swift)

On-device vector, text, and hybrid search for macOS and iOS, over LodeDB's native
Rust core. This is the published SwiftPM distribution: a thin package whose binary
target is the \`LodeDBCoreFFI.xcframework\` from the corresponding LodeDB release.

\`\`\`swift
.package(url: "https://github.com/Egoist-Machines/swift-lodedb", from: "${version}")
\`\`\`

Sources, tests, issues, and docs live in the main repository:
https://github.com/Egoist-Machines/LodeDB (see \`swift/LodeDBCore/README.md\` and
\`docs/swift-agent-contract.md\`). This package is generated from LodeDB ${version};
do not edit it here.
EOF

echo "Assembled swift-lodedb ${version} in ${staging} (xcframework: ${url})"
